### ISSUE TITLE
MAGNET MODE

### ISSUE THREAD

**Issue by ckhrix** [SpaceCat-Chan/SpaceCats-Tetris#1]
MAGNET MODE:
diffirent pieces are randomly asigned either negative or positive (signified by blue and red colors) and when a piece touches a static piece on the ground of the opposite color they disappear, and you cannot clear lines the classic way.
and when a piece of the same color touches one another the piece that was just placed gets pushed up one block in the y direction
and with edge cases idk its possible where they touch both but idk

**Comment by SpaceCat-Chan** [comment]
making two of the same polarity repel will be needlessly difficult
